begin;

create table if not exists public.website_projects (
  id bigint primary key generated by default as identity,
  slug text not null unique,
  title text not null,
  category text not null,
  location text,
  excerpt text,
  description text,
  image text not null default 'images/hero.jpeg',
  gallery jsonb not null default '[]'::jsonb,
  project_date text,
  status text not null default 'Dovršeno',
  equipment jsonb not null default '[]'::jsonb,
  specs jsonb not null default '[]'::jsonb,
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists website_projects_updated_at on public.website_projects;
create trigger website_projects_updated_at
before update on public.website_projects
for each row execute function public.set_updated_at();

alter table public.website_projects enable row level security;

drop policy if exists website_projects_public_read on public.website_projects;
create policy website_projects_public_read on public.website_projects
for select to anon, authenticated
using (true);

drop policy if exists website_projects_admin_insert on public.website_projects;
create policy website_projects_admin_insert on public.website_projects
for insert to authenticated
with check (public.is_organizer_admin());

drop policy if exists website_projects_admin_update on public.website_projects;
create policy website_projects_admin_update on public.website_projects
for update to authenticated
using (public.is_organizer_admin())
with check (public.is_organizer_admin());

drop policy if exists website_projects_admin_delete on public.website_projects;
create policy website_projects_admin_delete on public.website_projects
for delete to authenticated
using (public.is_organizer_admin());

insert into public.website_projects (
  id, slug, title, category, location, excerpt, description, image, gallery,
  project_date, status, equipment, specs, featured, sort_order
) values
  (1, 'priprema-terena-obiteljska-kuca', 'Priprema terena za obiteljsku kuću', 'Iskopi', 'Zagreb i okolica',
   'Strojni iskop, uklanjanje viška zemlje i precizno ravnanje terena uz postojeći objekt.',
   'Projekt je obuhvatio pripremu pristupa, strojni iskop i oblikovanje terena za nastavak građevinskih radova. Posebna pažnja posvećena je radu uz postojeći objekt i očuvanju sigurnog prolaza tijekom cijele izvedbe.',
   'images/g1.jpeg', '["images/g1.jpeg","images/g2.jpeg","images/g3.jpeg"]', '2025.', 'Dovršeno',
   '["Mini bager","Kompaktni utovarivač"]', '["Kontrolirani iskop","Ravnanje terena","Odvoz viška materijala"]', true, 1),
  (2, 'uklanjanje-betonske-povrsine', 'Uklanjanje betonske površine', 'Rušenja', 'Zagreb',
   'Kontrolirano razbijanje dotrajale betonske površine i priprema podloge za novu izvedbu.',
   'Dotrajala betonska površina uklonjena je hidrauličnim čekićem, nakon čega je materijal razvrstan i pripremljen za odvoz. Radovi su izvedeni u ograničenom prostoru uz pažljivo upravljanje strojem.',
   'images/g2.jpeg', '["images/g2.jpeg","images/slika2.jpeg","images/g4.jpeg"]', '2025.', 'Dovršeno',
   '["Bager s hidrauličnim čekićem"]', '["Strojno rušenje","Čišćenje površine","Priprema za novu podlogu"]', true, 2),
  (3, 'ravnanje-i-uredenje-dvorista', 'Ravnanje i uređenje dvorišta', 'Uređenje terena', 'Velika Gorica',
   'Planiranje dvorišta i priprema stabilne površine za završno krajobrazno uređenje.',
   'Nakon uklanjanja površinskog sloja teren je oblikovan prema potrebnim visinama i padovima. Završna obrada ostavila je prostor spreman za nastavak uređenja i postavljanje završnih slojeva.',
   'images/g3.jpeg', '["images/g3.jpeg","images/slika3.jpeg","images/g5.jpeg"]', '2025.', 'Dovršeno',
   '["Kompaktni utovarivač","Mini bager"]', '["Niveliranje","Formiranje padova","Fina priprema"]', true, 3),
  (4, 'iskop-kanala-za-instalacije', 'Iskop kanala za instalacije', 'Iskopi', 'Samobor',
   'Precizan linijski iskop uz kontrolu dubine i minimalno zauzimanje okolnog prostora.',
   'Izveden je kanal za polaganje instalacija uz unaprijed definiranu trasu. Kompaktna mehanizacija omogućila je brz rad i uredno odlaganje iskopanog materijala.',
   'images/g4.jpeg', '["images/g4.jpeg","images/hero.jpeg","images/g6.jpeg"]', '2024.', 'Dovršeno',
   '["Mini bager"]', '["Linijski iskop","Kontrola dubine","Uzak radni koridor"]', false, 4),
  (5, 'ciscenje-i-priprema-parcele', 'Čišćenje i priprema parcele', 'Uređenje terena', 'Zaprešić',
   'Uklanjanje površinskog sloja, čišćenje i organizacija parcele prije početka gradnje.',
   'Parcela je očišćena i pripremljena za geodetsko označavanje i prve građevinske zahvate. Materijal je organiziran tako da je omogućen siguran pristup svim dijelovima gradilišta.',
   'images/g5.jpeg', '["images/g5.jpeg","images/slika1.jpeg","images/g1.jpeg"]', '2024.', 'Dovršeno',
   '["Kompaktni utovarivač","Mini bager"]', '["Čišćenje parcele","Grubo ravnanje","Priprema pristupa"]', false, 5),
  (6, 'odvoz-zemlje-i-sute', 'Odvoz zemlje i građevinske šute', 'Odvoz', 'Sesvete',
   'Organizirano utovaranje i uklanjanje materijala nakon građevinskih zahvata.',
   'Višak zemlje i građevinski materijal uklonjeni su s lokacije uz koordinaciju utovara i odvoza. Radna zona je na kraju poravnata i ostavljena uredna.',
   'images/g6.jpeg', '["images/g6.jpeg","images/g3.jpeg","images/hero.jpeg"]', '2024.', 'Dovršeno',
   '["Mini bager","Transportno vozilo"]', '["Utovar materijala","Odvoz","Završno čišćenje"]', false, 6)
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.website_projects', 'id'),
  greatest(coalesce((select max(id) from public.website_projects), 1), 1),
  true
);

commit;
